MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  RPN_ONLY: True
  RPN:
    PRE_NMS_TOP_N_TEST: 12000
    POST_NMS_TOP_N_TEST: 2000
DATASETS:
  TRAIN: ("coco_2014_minival",)
  TEST: ("coco_2014_minival",)
INPUT:
  MIN_SIZE_TRAIN: 600
  MAX_SIZE_TRAIN: 1000
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1000
SOLVER:
  BASE_LR: 0.005
  WEIGHT_DECAY: 0.0001
  STEPS: (1500,)
  MAX_ITER: 2000
  IMS_PER_BATCH: 4
TEST:
  IMS_PER_BATCH: 2
